AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'deploy/**/*'
    - 'vendor/**/*'

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundMethodBody:
  Enabled: true

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*'

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'app/admin/*'
    - 'app/api/**/*'

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Max: 25

Naming/HeredocDelimiterNaming:
  Enabled: false

Performance/RedundantBlockCall:
  Enabled: false

Rails:
  Enabled: true

Rails/ApplicationRecord:
  Enabled: true

Rails/Delegate:
  EnforceForPrefixed: false

Rails/UnknownEnv:
  Environments:
    - production
    - staging
    - stg
    - development
    - dev
    - sandbox
    - test

Style/AndOr:
  Enabled: true

Style/AsciiComments:
  Enabled: false

Style/GlobalVars:
  Enabled: true

Style/ClassAndModuleChildren:
  Enabled: false

Style/ClassCheck:
  EnforcedStyle: kind_of?
  Enabled: true

Style/ClassVars:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/EachWithObject:
  Enabled: false

Style/EmptyCaseCondition:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/SignalException:
  EnforcedStyle: only_raise

Style/SingleLineBlockParams:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: percent
  MinSize: 10

Style/WordArray:
  EnforcedStyle: percent
  MinSize: 10

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/YodaCondition:
  EnforcedStyle: forbid_for_equality_operators_only

Style/NumericPredicate:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false
