AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'deploy/**/*'
    - 'vendor/**/*'

Rails:
  Enabled: true

# Rails5になるまでfalse
Rails/ApplicationRecord:
  Enabled: false

Style/AndOr:
  Enabled: true

Style/GlobalVars:
  Enabled: true

Style/ClassVars:
  Enabled: true

Style/Encoding:
  Enabled: true
  EnforcedStyle: never

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/EmptyLinesAroundClassBody:
  Enabled: false

Style/EmptyLinesAroundModuleBody:
  Enabled: false

Style/EmptyLinesAroundBlockBody:
  Enabled: false

Style/EmptyLinesAroundMethodBody:
  Enabled: true

Style/EmptyCaseCondition:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/SignalException:
  EnforcedStyle: only_raise

Style/EachWithObject:
  Enabled: false

Style/ClassCheck:
  EnforcedStyle: kind_of?
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/MultilineOperationIndentation:
  EnforcedStyle: indented

Style/MultilineMethodCallIndentation:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Max: 25

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Performance/RedundantBlockCall:
  Enabled: false
