AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'deploy/**/*'
    - 'vendor/**/*'

Rails:
  Enabled: true

# Rails5になるまでfalse
Rails/ApplicationRecord:
  Enabled: false

Rails/Delegate:
  EnforceForPrefixed: false

Style/AndOr:
  Enabled: true

Style/GlobalVars:
  Enabled: true

Style/ClassVars:
  Enabled: true

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundMethodBody:
  Enabled: true

Style/EmptyCaseCondition:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/SignalException:
  EnforcedStyle: only_raise

Style/EachWithObject:
  Enabled: false

Style/ClassCheck:
  EnforcedStyle: kind_of?
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/RescueModifier:
  Exclude:
    - 'spec/**/*'

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/MultilineMethodCallIndentation:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Max: 25

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Naming/HeredocDelimiterNaming:
  Enabled: false

Performance/RedundantBlockCall:
  Enabled: false
